# see documentation at https://goreleaser.com
project_name: wrangle

version: 2

before:
  hooks:
  # You may remove this if you don't use go modules.
  - go mod tidy
  # you may remove this if you don't need go generate
  - go generate ./...

builds:
- id: wrangle
  binary: wrangle
  main: ./cmd/wrangle
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64

archives:
- id: wrangle
  name_template: "{{.Binary}}-{{.Version}}-{{.Os}}-{{.Arch}}{{ if .Arm }}v{{.Arm }}{{ end }}"
  format: tar.gz
  builds: 
  - wrangle
  format_overrides:
  - goos: windows
    format: zip  

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: patrickhuber
    name: wrangle