FROM --platform=linux/amd64 ubuntu:22.04

ARG LOCAL

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl wget && \
    apt-get clean

ADD install.sh install.sh
RUN if [ "$LOCAL" = "true" ]; then \
        ./install.sh; \
    else \
        curl https://raw.githubusercontent.com/patrickhuber/wrangle/main/install.sh | bash; \
    fi