name: bosh
version: 5.3.1
targets:
- platform: linux
  tasks:
  - download:
      url: https://github.com/cloudfoundry/bosh-cli/releases/download/v((version))/bosh-cli-((version))-linux-amd64
      out: bosh-cli-((version))-linux-amd64
